# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqOY8vO0t3vD-ESJaqfocNVMMIDth0Te
"""

# app.py
import streamlit as st
import pandas as pd
import plotly.graph_objects as go

st.title("📈 Market Anomaly Dashboard (From CSV)")

# Upload CSV file
uploaded_file = st.file_uploader("📂 Upload your market_anomaly_alerts.csv", type="csv")

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file, parse_dates=True, index_col=0)

    # Show Close Price and Price Anomalies
    st.subheader("📉 Price with Detected Anomalies")

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=data.index, y=data['Close_AAPL'], mode='lines', name='Close Price'))

    if 'anomaly_price_' in data.columns:
        anomaly_points = data[data['anomaly_price_'] == -1]
        fig.add_trace(go.Scatter(x=anomaly_points.index, y=anomaly_points['Close_AAPL'],
                                 mode='markers', name='Price Anomaly',
                                 marker=dict(color='red', size=6)))

    fig.update_layout(title="Price Chart with Anomalies", xaxis_title='Time', yaxis_title='Price')
    st.plotly_chart(fig)

    # Show alerts table
    st.subheader("📋 Latest Alerts")
    st.dataframe(data.tail(20))

else:
    st.warning("⬆️ Please upload the CSV file to begin.")